language: python
python:
- '3.5'
- '3.6'

install:
- hash -r
- pip install pipenv==11.1.5
- pipenv install -e .[test]

script:
- python setup.py test
- coverage run --source=piecash setup.py test

after_success: coveralls

sudo: false

deploy:
  provider: pypi
  user: sdementen
  password:
    secure: JDJrFwdiEbyY6T3GE+XJv6lX/EpyjMeADGRKXZKalKebbGXqxG1198DaC0zKi2CwWQ57qv1z2JvCr2xDkw5zn5o/0DFdONnQegz+PtNUP+LvRCqoxo8wYGwYmKGmBSCfXI9j0jsfuE3xqx7KRwHMNGlrfBVETo6fTsngaEqPY3g=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: sdementen/finance-quote
    all_branches: master
    condition: $PYTHON_VERSION=3.5
